### ISSUE TITLE
Unrepresentative avatar

### ISSUE THREAD

**Issue by Hirohitonaj** [frankos6/blanciorgancior#3]
The avatar of Musialik's profile is wrong and compeletly unrepresentative. I would like you to change an avatar to this:

![172px-Hirohito_in_dress_uniform](https://user-images.githubusercontent.com/98818923/170499016-1d0d8f13-e506-4eeb-b8d0-6fa9c7c90716.jpg)

**Comment by frankos6** [comment]
Done :D
